blank_issues_enabled: false
contact_links:
  - name: Report a Bug or Issue
    url: https://github.com/hesreallyhim/github-minesweeper/discussions
    about: Please open a discussion topic to report any issue, since the issues tab is effectively part of the game surface
