blank_issues_enabled: false
contact_links:
  - name: Report a Bug or Issue
    url: https://github.com/hesreallyhim/github-minesweeper/discussions/30
    about: Please open a discussion topic to report any issues, since this repository uses issues for gameplay.
  - name: Request a Feature
    url: https://github.com/hesreallyhim/github-minesweeper/discussions/28
    about: Want to request a feature? Have an idea on how to improve the game or the repository? We've got a thread for that too!
